# error-with-cause

`ErrorWithCause` extends `Error` with a cause.
